### ISSUE TITLE
Teamspeak tag length limit prevents validation on long names.

### ISSUE THREAD

**Issue by jasonmcalpin** [warlof/seat-teamspeak#10]
* **Problem**: Teamspeak has a limit to the length of the tag. It limits the name to 30 characters.
* **Expected**: Seat-teamspeak should use the same limit when verifying the character name on Teamspeak
I used the character name: 
X-XXX | Seanachaidh MacStarling 
But Teamspeak can only take:
X-XXX | Seanachaidh MacStarlin

By going for the longest spelling possible for my name I discovered that there is a character limit in Teamspeak.

**Comment by hderp886** [comment]
#12 < PR contains fix for this error.
