### ISSUE TITLE
Access Management Page Issue

### ISSUE THREAD

**Issue by JacobOkanta** [warlof/seat-teamspeak#13]
After adding in the query information, and updating roles, when trying to open the access management sub-menu i get an error "Whoops looks like something went wrong" I installed both the discord and teamspeak connector on SeAT with a docker install using the instructions to install from the docker admin guide for installing plugins.

**Comment by JacobOkanta** [comment]
Where can I find them?

**Comment by warlof** [comment]
https://eveseat.github.io/docs/troubleshooting/

**Comment by JacobOkanta** [comment]
Here are both log files eseye and laravel though I believe you need the laravel i brought both just in case.

[eseye-2018-10-12.log](https://github.com/warlof/seat-teamspeak/files/2474658/eseye-2018-10-12.log)
[laravel-2018-10-12.log](https://github.com/warlof/seat-teamspeak/files/2474659/laravel-2018-10-12.log)

**Comment by warlof** [comment]
Despite none of the entries from laravel log are related to the teamspeak plugin; it appears you mist a lot of table in your database.

Did you run migrations ?!

**Comment by JacobOkanta** [comment]
No I used the docker install command (bash <(curl -fsSL https://git.io/seat-docker)
 from the docs here https://eveseat.github.io/docs/installation/docker_installation/ then put relevant information into the .env file (Plugins and SSO app configuration) and finally ran docker-compose up -d

**Comment by warlof** [comment]
so, run migrations.

Things will work much better for all of your plugins actually.

**Comment by JacobOkanta** [comment]
Yes all is working now except when I go to configure the roles alliance is not showing up as an option only corporation, when I click on Alliance all I get is "No Results Found"
