### ISSUE TITLE
clas sseat\services\abstractseatplugin ?

### ISSUE THREAD

**Issue by dstevens79** [warlof/seat-teamspeak#18]
cannot find this while updating to latest

plz help

**Comment by herpaderpaldent** [comment]
Can you provide the packages versions please?
If you go into settings > SeAT Settings you'll get details related to SeAT packages and a copy button near them. Use it and paste the content put into your clipboard here.

**Comment by dstevens79** [comment]
i did an update of everything on thse server including seat itself and this was resolved - everything claimed it was up to date but ... was not i guess?

Thank you for all the epic work on seat and its plugins
Please lmk if i can help in any way
